### PR TITLE
Makefile save function sets the PROJ variable in the Makefile to the actual name the project was saved with.

### PR DESCRIPTION
**Pull request by elmbeech**
This pull request is written on top of pull request #244 and addresses issue #222 .
What the pull request solves:

**The Makefile save function now sets the PROJ variable in the Makefile to the actual name the project was saved with.**

Before when e.g. a project was saved with
```
make save PROJ=abc
```
the save project had his PROJ variable still set to
```
PROJ := my_project
```
or whatever the PROJ variable was set before.
Now the saved project will have set the PROJ variable correctely to 
```
PROJ := abc
```
as it should be.

**This is a crucial change because it will prevent users from down the road overwriting accidentally the original project from which the newly saved project was derived from.**

@rheiland, because this changes use a sed command, cloud you, please check if this works on the Windows bash shell and on MacOSX zsh shell? That would be very helpful!

### CODE REVIEW

**Comment by rheiland** [comment]
The sed command does indeed seem to work on my Windows machine. But I'm still a bit confused. When I did `make save PROJ=foo`, it updates the Makefile in the foo user_project, but wouldn't you also want to update the root's Makefile so that one could then just do `make save` and have it update the foo user_project?

**Comment by drbergman** [comment]
Looks like a very thorough set of changes and a nifty way to make it easier to use `make save`. I see you're also including `make clean` inside `make reset`. Did I miss the conclusion of #212?

**Comment by elmbeech** [comment]
@rheiland, that is a good point. I can do the change to the Makefiles before I copy to the users_project folder.

@drbergman , there was no "conclusion" just expressed your opinion. 
if you do a reset, to work on a now project, it could simply cause errors if you have binaries from lying around from a project you worked before. or can you name me a PhysiCell project you work on, you still want to have the binaries around after a reset?  since i had to rewrite the whole function, I attempted to do a clean reset. and as i wrote in #212, it will not break your habits. you can do make clean, as much as you want, make clean reset as much as you want, and you can make rest as much as you want.

**Comment by rheiland** [comment]
On my Mac, the native `sed` fails:
```
M1P~/dev/PhysiCell-patch_proj_name$ make save PROJ=foo
echo "Saving project as foo ... "
Saving project as foo ... 
mkdir -p ./user_projects
mkdir -p ./user_projects/foo
mkdir -p ./user_projects/foo/custom_modules
mkdir -p ./user_projects/foo/config 
cp main.cpp ./user_projects/foo
cp Makefile ./user_projects/foo
sed -i "0,/PROJ := /{s/PROJ := .*/PROJ := foo/}" ./user_projects/foo/Makefile
sed: 1: "./user_projects/foo/Mak ...": invalid command code .
make: *** [save] Error 1
```
I remember now that for a past project, I had to brew install the gnu sed to do what I wanted.

So this `sed`-related PR, as is, should not be merged.

**Comment by elmbeech** [comment]
yes @rheiland, this is the exact same error we had last time.
I wonder if it is related to zsh. will track this down.
thank you for the report!

**Comment by elmbeech** [comment]
well, we would have to figure out if the GNU sed or the BSD sed is installed.
this is getting `awkward` - so I will to try to find a way to achive the same with awk, hoping the GNU and the BSD awk will behave the same, and hoping that awk is installed on Windows.

**Comment by elmbeech** [comment]
@rheiland i just pushed the changes. 
could you please give another try?

**Comment by rheiland** [comment]
On my  Mac, native `awk` fails:
```
(base) M1P~/git/elmar_patch_proj_name$ make save PROJ=hetero
echo "Saving project as hetero ... "
Saving project as hetero ... 
mkdir -p ./user_projects
mkdir -p ./user_projects/hetero
mkdir -p ./user_projects/hetero/custom_modules
mkdir -p ./user_projects/hetero/config 
cp main.cpp ./user_projects/hetero
awk -i inplace '{gsub("^PROJ :=.*$", "PROJ := hetero", $0); print $0}' Makefile
awk: unknown option -i ignored

awk: can't open file {gsub("^PROJ :=.*$", "PROJ := hetero", $0); print $0}
 source line number 1
make: *** [save] Error 2
```
```
(base) M1P~/git/elmar_patch_proj_name$ which awk
/usr/bin/awk
(base) M1P~/git/elmar_patch_proj_name$ awk --version
awk version 20200816
```

**Comment by elmbeech** [comment]
why the heck Berkeley Software Distribution?

**Comment by elmbeech** [comment]
at least on Windows it seems to work. 
Will try to work on a workaround that works on all OSes.

**Comment by MathCancer** [comment]
I don't understand the purpose of this PR and change. 

I think it's a *bad* idea to overwrite the Makefile. 

PROJ defaults to my project unless you use a command-line argument. The command line argument always works. What problem are we trying to solve here?

**Comment by elmbeech** [comment]
ok. I think you understood what my intention was.

i always understood a 
+ `make save PROJ=abc` as `save as`
+ `make save` as `save`
obviously, this is not how you want to run things.

(look in now over the whole Makefile, i wonder why we actually have two variables `PROGRAM_NAME` and `PROJ`. Would it not simplify things, if this was one single variable?)

anyhow,  I will drop this pull request but keep the  #244 pull request alive, which solves the deep folder structure. 

thank you, Elmar

**Pull request closed without merging**
