### PR TITLE
changes to the cp command from make save and make load to allow user project config and custom_modules with a folder structure version2.

### PR DESCRIPTION
**Pull request by elmbeech**
This pull request now has the Makefile-default, the Makefile, all sample_projects Makefiles, all  
sample_projects_intracellular Makefiles, and all unit_test Makefiles changed accordingly.

### CODE REVIEW

**Comment by elmbeech** [comment]
Replaces pull request #230 .
For more information, please read the discussion there.

**Comment by elmbeech** [comment]
this pull request is not ready!
because all Makefiles have not to allow deep folder structure for custom_modules and config, the reset function have to be adjusted too. 
I will work on this today.

**Comment by elmbeech** [comment]
why is the Makefile-default duing this:
```
rm -f *.cpp PhysiCell_cell.o
touch ./core/PhysiCell_cell.cpp 
````

while most of the other reset functions i have seen just do this:
```
rm -f *.cpp 
touch ./core/PhysiCell_cell.cpp 
```

**Comment by elmbeech** [comment]
The `reset` and `checkpoint` functions in all Makefiles (Makefile-default, Makefile, sample_projects, sample_projects_intracellular, unit_test) are now updated so that they are compatible with the config and custom_modules deep folder structure.

`this pull request is ready to be merged into the development branch`.

**Comment by elmbeech** [comment]
the reset function in all Makefiles  (Makefile-default, Makefile, sample_projects, sample_projects_intracellular, unit_test)  are now independent of an existing `PhysiCell_settings-backup.xml`.
the function will use `sample_projects/PhysiCell_settings.xml-default` for restore.

`this pull request is ready to be merged into the development branch.`

**Comment by rheiland** [comment]
I tested the `make save PROJ=foobar` (and `make load ...`) and confirmed the recursive copy works on Windows.

However, any Makefile target using `zip`, e.g., `make checkpoint` fails on my machine using both Command Prompt and Powershell, as the `zip` command is apparently not present in a native system.

**Comment by drbergman** [comment]
So, this would be a bug that currently exists. Is that correct?

**Comment by rheiland** [comment]
Yes

**Comment by MathCancer** [comment]
We disagree with forcing "make clean" bevore "make reset" 

Reject until next physicell release. sorry.

**Comment by elmbeech** [comment]
ok.

**Pull request closed without merging**
