### PR TITLE
template project code automatically generates output folder if it doesn't exist version2

### PR DESCRIPTION
**Pull request by elmbeech**
This PR should now work on all platforms and replaces [PR #235](https://github.com/MathCancer/PhysiCell/pull/235).
For more information, please read the discussion from 235.

In addition, this PR integrates pull request [Github action to build and run template project on all 3 OS #241](https://github.com/MathCancer/PhysiCell/pull/241)

### CODE REVIEW

**Comment by rheiland** [comment]
Yes, this worked for me on my Windows/MinGW machine for the template project, i.e., I totally deleted the `output` folder and the template `project` created it as expected.

**Comment by MathCancer** [comment]
Conflict on template project main.cpp 

Can someone give it a look beore we approve the PR, please?

**Comment by elmbeech** [comment]
Superseded with pull request #246 and therefore closed.

**Comment by MathCancer** [comment]
Thank you, Elmar!

**Comment by elmbeech** [comment]
Thank you, Paul!

**Pull request closed without merging**
