### PR TITLE
Custom adhesion and repulsion functions

### PR DESCRIPTION
**Pull request by vincent-noel**
This PR adds two new custom functions, to compute adhesion and repulsion. 

This time I left the original function if the pointer is null, and didn't create a "standard" function. But I can change that if you think it's better.

### CODE REVIEW

**Comment by MathCancer** [comment]
Huh, let's catch up in via video first.

**Comment by MathCancer** [comment]
preferred design: 

Make a custom mechanics function that uses your preferred repulsion, etc. 
Then for some cell definition CD, set: 

CD.functions.update_velocity = noels_new_mechanics_function. 

Don't modify the existing functions or add a new function pointer to Cell_Functions unless completely necessary.

**Review by MathCancer — CHANGES_REQUESTED** [review]
preferred design:

Make a custom mechanics function that uses your preferred repulsion, etc.
Then for some cell definition CD, set:

CD.functions.update_velocity = noels_new_mechanics_function.

Don't modify the existing functions or add a new function pointer to Cell_Functions unless completely necessary.

**Comment by MathCancer** [comment]
What's the status on this? 

No longer needed, now that we have 1.9.0 out? 

I'm closing this if I don't hear otherwise. Thanks!

**Comment by MathCancer** [comment]
Where do we stand on this one @vincent-noel ? 

Still needed?

**Comment by vincent-noel** [comment]
When I made this PR, I was thinking it would be nice to only customize adhesion or repulsion functions. But as you said, it's probably unnecessary complexity, and just using a custom update_velocity is simpler.
You can close it.

**Pull request closed without merging**
