### PR TITLE
Arg parse and make output folder

### PR DESCRIPTION
**Pull request by drbergman**
Move argument parsing to new class `ArgumentParser` in `modules/PhysiCell_settings.h`. This handles the config file as arg away from `main.cpp` making that file simpler for users. Also, can pass the output folder as an arg (prefixed by a `-o` flag). Or still set within the config file. Future features are commented (pass in rules, ics, etc as command line args)

This also implements the creating of the output folder if it doesn't exist. This implementation creates the necessary folder structure, i.e. creates all necessary intermediate folders if they don't yet exist.

### CODE REVIEW

**Comment by drbergman** [comment]
this is 100% backwards compatible. see testing here: https://github.com/drbergman/PhysiCell/tree/test-arg-parse

this tested every permutation of args. from `.github/workflows/test-ubuntu.yml`
```
    - name: Run ArgParse project no arguments
      run: |
        ./project

    - name: Run ArgParse project with unflagged config file
      run: |
        ./project ./config/PhysiCell_settings.xml

    - name: Run ArgParse project with flagged config file
      run: |
        ./project -c ./config/PhysiCell_settings.xml

    - name: Run ArgParse project with flagged output directory
      run: |
        ./project -o output/test/the/arg/parser

    - name: Run ArgParse project with unflagged config file and output directory
      run: |
        ./project ./config/PhysiCell_settings.xml -o output/test/the/arg/parser

    - name: Run ArgParse project with flagged config file and output directory
      run: |
        ./project -c ./config/PhysiCell_settings.xml -o output/test/the/arg/parser
```

**Comment by drbergman** [comment]
this is not for an output folder with subfolders, but if the output folder is being placed inside a folder that does not yet exist. for example, if the output folder is located at `<folder>./new_folder_for_a_bunch_of_outputs/simulation_1/output</folder>` then `new_folder_for_a_bunch_of_outputs`, `simulation_1`, and `output` folders will be created if they do not exist.

**Comment by elmbeech** [comment]
ogge! got ya! all fine with me.

**Comment by rheiland** [comment]
Should this work for any project? On Windows, I just built the default heterogeneity project and get:
PS C:\Users\randy\git\daniel_arg-parse-and-make-output-folder> .\heterogeneity.exe -o hetero1
Using config file -o ...
Error loading -o!

But testing the template project does work as expected.

**Comment by drbergman** [comment]
yeah, it needs a change to the main files there (just the first few lines reading in the config file. I'll make changes so that future workshops, etc. could use this syntax even with these sample projects

**Comment by MathCancer** [comment]
wait for now. 

and probably `cp -r config` to the output directory

**Pull request closed without merging**
